fix: load-more button added in place of infinite scroll
openedx/frontend-app-discussions pull request #199
Opened 2022-06-21 17:05 UTC by mehaknasir

To resolve accessibility issues with loading more threads a visible element is added as load more button to help resolve the issue. 
<img width="453" alt="Screenshot 2022-06-21 at 10 04 51 PM" src="https://user-images.githubusercontent.com/67791278/174857452-8772ac3b-2701-4fd2-9097-8f744de9a48f.png">

2022-06-22 01:55 UTC, muhammadadeeltajamul approved these changes

2022-06-22 09:14 UTC, awais-ansari requested changes
Please add `Show more` button in the learners area too.

2022-06-22 10:38 UTC, asadazam93 approved these changes
Just one question. Rest looks good

2022-06-22 10:38 UTC, asadazam93 commented on src/discussions/posts/PostsView.jsx
> -import ScrollThreshold from '../../components/ScrollThreshold';
Should we remove ScrollThreshold component? Or is it used somewhere else?

2022-06-22 10:38 UTC, asadazam93 commented
@mehaknasir Can you please link the related ticket?

2022-06-22 11:29 UTC, mehaknasir commented
> @mehaknasir Can you please link the related ticket?

I think it was in use in some other places.  but I am making a change as suggested by Awais so will look if there are any more places where its being used.

2022-06-24 13:16 UTC, awais-ansari approved these changes

2022-06-24 16:48 UTC, merged