fix: updated pinned post icon
openedx/frontend-app-discussions pull request #212
Opened 2022-07-19 06:25 UTC by muhammadadeeltajamul

Ticket Link:
https://2u-internal.atlassian.net/browse/INF-354

![new_pinned_icon](https://user-images.githubusercontent.com/77053848/179680373-66840578-1880-4b49-a53f-e3006ecdaad3.png)

2022-07-19 14:41 UTC, awais-ansari requested changes

2022-07-19 14:41 UTC, awais-ansari commented on src/discussions/posts/post/PostLink.jsx
> +              )}
We are using 20x20 icons in the post summary card. Please use the `icon-size` class which will set the icon height and width. Please make sure the height should not exceed 22px.

2022-07-21 07:04 UTC, awais-ansari approved these changes

2022-07-22 09:21 UTC, mehaknasir approved these changes

2022-07-22 09:33 UTC, merged