fix: post avatar alignment and size
openedx/frontend-app-discussions pull request #214
Opened 2022-07-20 11:44 UTC by awais-ansari

**[INF-339](https://2u-internal.atlassian.net/browse/INF-339)**
**[INF-347](https://2u-internal.atlassian.net/browse/INF-347)**

1. Question icon and the avatar image size are the same in size. The total size is 26px including the border.
2. Question icon has the same border color as its background.
3. Avatar border is different from the background color that why it is more visible.

**Updated UI**
<img width="470" alt="Screenshot 2022-07-20 at 4 33 54 PM" src="https://user-images.githubusercontent.com/79941147/179973923-aab9f103-e007-4f7f-85ac-70696d6b890f.png">
<img width="921" alt="Screenshot 2022-07-20 at 4 34 10 PM" src="https://user-images.githubusercontent.com/79941147/179973940-b690937b-102f-4823-a936-79444fce99ab.png">
<img width="919" alt="Screenshot 2022-07-20 at 4 34 20 PM" src="https://user-images.githubusercontent.com/79941147/179973945-e33a91a5-fa63-422f-ba21-956e11f9e1bb.png">
<img width="936" alt="Screenshot 2022-07-20 at 4 34 30 PM" src="https://user-images.githubusercontent.com/79941147/179973950-b519142b-79a9-4880-9133-6e93b73aacbe.png">

2022-07-22 09:32 UTC, mehaknasir requested changes

2022-07-22 09:32 UTC, mehaknasir commented on src/discussions/posts/post/PostHeader.jsx
> +      : post.type === ThreadType.DISCUSSION && 'ml-0.5 mt-0.5'}`}
import classNames from 'classnames';
and then className={ 'pt-2 ml-0.5': post.type === ThreadType.DISCUSSION && fromPostLink,
        'ml-0.5 mt-0.5': post.type === ThreadType.DISCUSSION,}
        
        also will suggeste calculating position above in component for classes to practice cleancode.

2022-07-22 09:32 UTC, mehaknasir commented on src/discussions/posts/post/PostHeader.jsx
>              left: fromPostLink ? '14px' : '',
make two different classes each with the attributes required and then  pass here as conditional classes. the code is not looking clean with all these styling tags and conditions.

2022-07-26 11:53 UTC, mehaknasir approved these changes

2022-07-26 12:00 UTC, asadazam93 approved these changes

2022-07-26 12:01 UTC, merged