feat: add support for question type posts [BD-38] [TNL-8723] [BB-4884]
openedx/frontend-app-discussions pull request #22
Opened 2021-09-21 04:43 UTC by xitij2000

Question type posts/thread need special handling since they deal with endorsed and un-endorsed comments separately. We need to track pagination for endorsed and unendorsed comments separately, and display endorsed comments above all others. 

**JIRA tickets**: 
- [TNL-8723](https://openedx.atlassian.net/browse/TNL-8723)

**Dependencies**: 
- #19 makes a lot of UI changes to the affected pages here
- #20  adds support for pagination and this touches pagination a lot

So the above two PRs should be merged before this PR can be finalised.

**Screenshots**: 

https://user-images.githubusercontent.com/118837/135241028-5b60a92a-e6e5-4a20-b543-ceb67fc2e68a.mp4

This PR includes UI changes to align the UI closer to the newer designs. However, the aim currently isn't to reach a 100% match, but mainly to make incremental changes that mostly change the pages that were already touched. 

**Testing instructions**:

1. Create a question type post
2. Add endorsed and unendorsed replies to it using the existing forum interface at `/courses/{course_id}/discussion/forum/`
2. Make sure that both endorsed and un-endorsed comments are showing up 

**Reviewers**
- [ ] (OpenCraft internal reviewer's GitHub username goes here)
- [ ] edX reviewer[s] TBD

2021-09-21 04:44 UTC, edx-webhook commented
Thanks for the pull request, @xitij2000! I've created [BLENDED-965](https://openedx.atlassian.net/browse/BLENDED-965) to keep track of it in Jira.   More details are on the [BD-38](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2790490201/BD-38+Discussions+In-Context+Discussion+Moderation+Phase+2) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


<!-- comment:welcome-blended -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2021-09-28 09:57 UTC, xitij2000 commented on src/discussions/comments/CommentsView.test.jsx
> +  Factory.build('commentsResult', null, {
I personally looked at `frontend-app-learning` :-)

2021-09-29 16:47 UTC, farhaanbukhsh approved these changes
👍 

- ✅  I tested this on my local devstack, I tried endorsing the answers.
- ✅  I read through the code
- ❌  I checked for accessibility issues
- ❌  Includes documentation
- ❌  I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

2021-09-29 18:02 UTC, mehaknasir requested changes
I have noticed some issues in design and features
message path is incorrect for errors in response and comments
<img width="1072" alt="Screenshot 2021-09-29 at 10 36 28 PM" src="https://user-images.githubusercontent.com/67791278/135323471-30e86df2-a9be-4b82-a0ad-9723712c6ef6.png">


I am seeing multiple react errors in console I think we should keep that in check as well
<img width="469" alt="Screenshot 2021-09-29 at 10 59 36 PM" src="https://user-images.githubusercontent.com/67791278/135323695-eab4fdae-1987-48f2-bdae-c1ecc4b93d31.png">

lastly, the UI looks much better now but the sidebar design still needs fixing
see the down arrow in screenshot
<img width="379" alt="Screenshot 2021-09-29 at 11 01 23 PM" src="https://user-images.githubusercontent.com/67791278/135323926-50b70789-9773-4f31-b41d-e9086c3b35b1.png">

2021-09-30 16:03 UTC, xitij2000 commented on src/discussions/comments/comment/Comment.jsx
> +          )}&nbsp;
Not really. Not unless there are new mechanism for future post types.

2021-09-30 16:04 UTC, xitij2000 commented on src/discussions/comments/data/redux.test.js
> +    await executeThunk(fetchThreadComments(threadId, { endorsed: true }), store.dispatch, store.getState);
It is not repeated, the first line as endorsed set to false, and the second has it set to true.

2021-09-30 16:05 UTC, xitij2000 commented
@mehaknasir  The error messages and the overflowing arrow are all due to the existing filter bar which is based on the older designs and will be replaced with the new filter design in another ticket.

2021-10-01 09:56 UTC, mehaknasir requested changes
https://github.com/edx/frontend-app-discussions/pull/23#discussion_r719455894
In reference to the conversation on PR#23 as this is part of this PR I would like to have this change

2021-10-06 14:20 UTC, merged