feat: nav bar added as a separate component in discussion
openedx/frontend-app-discussions pull request #222
Opened 2022-07-27 19:07 UTC by mehaknasir

TNL- TICKET: https://2u-internal.atlassian.net/browse/INF-336

Navbar is added screenshot attached

<img width="1440" alt="Screenshot 2022-07-28 at 12 00 20 AM" src="https://user-images.githubusercontent.com/67791278/181351297-0f01592f-8179-4094-b7a5-b1a2df21dd44.png">

PENDING: Flag-based navbar rendering required.

2022-07-29 10:50 UTC, awais-ansari requested changes

2022-07-29 10:50 UTC, awais-ansari commented on src/components/NavigationBar/data/thunks.js
> +      const courseHomeCourseMetadata = await getCourseHomeCourseMetadata(courseId, 'outline');
For multiple uses of this component in other MEF, we need to make this hard-coded `outline` into param.

2022-07-29 10:50 UTC, awais-ansari commented on src/index.scss
> +    border-right: 0;
move all Scss related to the navigation bar into a separate independent Scss file.

2022-08-01 09:51 UTC, awais-ansari approved these changes

2022-08-04 09:02 UTC, mehaknasir commented on src/discussions/discussions-home/DiscussionsHome.jsx
> +  const inIframe = new URLSearchParams(location.search).get('inIframe') !== null;
yes

2022-08-04 09:11 UTC, merged