feat: added blackout dates implementation
openedx/frontend-app-discussions pull request #271
Opened 2022-08-25 12:00 UTC by AhtishamShahid

2022-08-29 09:11 UTC, mehaknasir approved these changes

2022-08-29 09:13 UTC, awais-ansari requested changes

2022-08-29 09:13 UTC, awais-ansari commented on src/discussions/utils.js
> +  return date > start && date < end;
This condition will exclude the blackout start and end date.  e.g blackout date starts from `3-08-2022` and the current date also is `3-08-2022`. '3-08-2022' > '3-08-2022' will be false. However, It is on a blackout date.
So condition should be like 
`date >= start && date =< end`

2022-08-29 09:13 UTC, awais-ansari commented on src/discussions/comments/comment/ResponseEditor.jsx
> +      ) : null
nit:
`!inBlackoutDateRange(blackoutDateRange) && (
        <div className={classNames({ 'mb-4': addWrappingDiv }, 'actions d-flex')}>
          <Button variant="primary" className="px-2.5 py-2" onClick={() => setAddingResponse(true)}>
            {intl.formatMessage(messages.addResponse)}
          </Button>
        </div>
      ) `

after that, you will not need to comment eslint. ` // eslint-disable-next-line no-nested-ternary`

2022-08-31 13:28 UTC, awais-ansari approved these changes

2022-09-01 14:58 UTC, merged