feat: copy post functionality
openedx/frontend-app-discussions pull request #280
Opened 2022-09-05 08:40 UTC by muhammadadeeltajamul

"Copy link" functionality in list of actions for posts. Comment actions should not show "copy link"
ac62-32384ec5670d.png)

Ticket Link:
https://2u-internal.atlassian.net/browse/INF-299

Backend PR:
https://github.com/openedx/edx-platform/pull/30941

For Post
![copy_thread](https://user-images.githubusercontent.com/77053848/188406828-cc3951c4-6bae-41b5-be85-23ea40588bae.png)

For comment
![copy_comment](https://user-images.githubusercontent.com/77053848/188406787-46d76a4e-3783-4e99-

2022-09-08 11:57 UTC, asadazam93 approved these changes

2022-09-08 12:35 UTC, mehaknasir requested changes
do we have test cases for dropdown component? if yes can you please add test cases for this ticket?
https://github.com/openedx/frontend-app-discussions/pull/280/files
copy link should be visible in and working in  post actions
copy link should not be visible in comments

2022-09-09 11:39 UTC, muhammadadeeltajamul commented
> do we have test cases for dropdown component? if yes can you please add test cases for this ticket? https://github.com/openedx/frontend-app-discussions/pull/280/files copy link should be visible in and working in post actions copy link should not be visible in comments

Added test cases

2022-09-12 07:29 UTC, mehaknasir approved these changes

2022-09-12 07:31 UTC, merged

2022-09-12 07:34 UTC, saadyousafarbi approved these changes
:shipit: