fix: match discussion header with learning header
openedx/frontend-app-discussions pull request #299
Opened 2022-09-22 11:21 UTC by muhammadadeeltajamul

Match discussions header with learning MFE header

Ticket
https://2u-internal.atlassian.net/browse/INF-501

Sample output
![sample](https://user-images.githubusercontent.com/77053848/191733785-2bb20c5b-bebc-47bb-b083-5acce1e3108a.gif)

2022-09-22 13:02 UTC, awais-ansari requested changes

2022-09-22 13:02 UTC, awais-ansari commented on src/index.scss
> +}
You can group classes in SCSS. 

.learning-header {
  margin-left: -1.25rem;
  margin-right: -1.25rem;
  padding-top: 1 rem;
  line-height: 1;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  font-size: 18px;
  height: 60px;

  .container-xl {
    span {
      line-height: 1;
    }

    .logo {
      margin-top: 4px;
    }
  }

  span:first-child {
    font-size: 87.5%;
    margin-top: 2px !important;
    margin-bottom: -2px !important;
  }
}
`

2022-09-23 09:50 UTC, awais-ansari approved these changes

2022-09-23 11:35 UTC, asadazam93 approved these changes

2022-09-23 11:48 UTC, merged

2022-09-23 14:22 UTC, e0d commented
@muhammadadeeltajamul is there a plan to address the failed code coverage check?