fix: ui refactoring of load more responses and comments button
openedx/frontend-app-discussions pull request #310
Opened 2022-10-03 08:35 UTC by muhammadadeeltajamul

UI Refactoring 
- Corrected text for load more comments button
- Moved "Add a response" button below "Load more responses" button
- Change UI of "Load more responses", "Load more comments", "Add a response" and "Add a comment" button according to figma

Before
![inf-547_before](https://user-images.githubusercontent.com/77053848/193534576-92d17382-3c3d-4304-8be1-b9903ef68018.png)

After
![inf-547_after](https://user-images.githubusercontent.com/77053848/193534595-28fde523-da68-4b67-b757-9d98fdd3c188.png)

2022-10-03 13:09 UTC, awais-ansari requested changes

2022-10-03 13:09 UTC, awais-ansari commented on src/index.scss
> +}
This change is unnecessory because the link will have the same color code after applying the theme.

2022-10-04 12:53 UTC, mehaknasir approved these changes

2022-10-05 05:22 UTC, muhammadadeeltajamul commented on src/discussions/comments/CommentsView.jsx
> +            }}
Line height is needed. Without adding this property, the height of element decreases upto 1.333 px.

2022-10-05 05:23 UTC, muhammadadeeltajamul commented on src/discussions/comments/comment/ResponseEditor.jsx
> +        >
Total height of element decreases upto 1.333 px

2022-10-05 05:23 UTC, muhammadadeeltajamul commented on src/discussions/comments/comment/Comment.jsx
> +                      }}
Total height of element decreases upto 1.333 px

2022-10-05 08:46 UTC, awais-ansari approved these changes

2022-10-05 08:51 UTC, merged