fix: removed highlighted header-action-bar on confirmation pop-up
openedx/frontend-app-discussions pull request #337
Opened 2022-10-25 06:43 UTC by ayeshoali

### [INF-646](https://2u-internal.atlassian.net/browse/INF-646)

- On Delete  only confirmation pop-up highlights

**Before Fix:**

![before](https://user-images.githubusercontent.com/73840786/197700217-635d5e84-28ef-48be-9e23-572505f907d2.png)

**After Fix:**
<img width="1678" alt="Screenshot 2022-10-25 at 11 20 28 AM" src="https://user-images.githubusercontent.com/73840786/197700883-cd8cb366-e361-4454-9c72-8b3a4df25172.png">

<img width="1678" alt="Screenshot 2022-10-25 at 11 20 14 AM" src="https://user-images.githubusercontent.com/73840786/197700255-fb89faa2-7b21-4263-aff2-35ae79e69c4e.png">

2022-10-25 06:43 UTC, openedx-webhooks commented
Thanks for the pull request, @ayeshoali!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-10-26 09:59 UTC, awais-ansari requested changes
Please test this change for the post-content menu dropdown. The post content menu dropdown and header were overlapping because of the z-index.

2022-10-26 14:19 UTC, awais-ansari approved these changes
LGTM

2022-10-26 14:48 UTC, ayeshoali commented on src/index.scss
> +
Removed

2022-11-01 13:39 UTC, merged