Topic information moved next to username
openedx/frontend-app-discussions pull request #341
Opened 2022-11-01 10:41 UTC by ayeshoali

### [INF-528](https://2u-internal.atlassian.net/browse/INF-528)

The cohorts section works differently based on whether or not cohorts are enabled for the course.

> Topic info moved next to the username, for posts in content-specific discussion topics
> Changes made to accommodate 3-level topic hierarchy, once in-context discussions is enabled.
> Long topic names are truncated appropriately.

**Before Fix:**
![Unknown](https://user-images.githubusercontent.com/73840786/199215328-30a1ae29-6bf2-43a2-a750-a45641057e0a.png)

**After Fix:**

<img width="1230" alt="Screenshot 2022-11-01 at 3 39 09 PM" src="https://user-images.githubusercontent.com/73840786/199215633-23c86232-d856-4cca-90cd-d59583fc232e.png">

2022-11-02 15:29 UTC, mehaknasir requested changes

2022-11-02 15:29 UTC, mehaknasir commented on src/discussions/posts/post/PostHeader.jsx
> +              </Hyperlink>
this PR is only fixing the design for when in-context is enabled? what about use case when in-context discussion are bot enabled?

2022-11-03 11:47 UTC, mehaknasir approved these changes

2022-11-03 12:02 UTC, mehaknasir commented
@ayeshoali thee branch needs rebasing beforee merge.

2022-11-08 08:58 UTC, awais-ansari requested changes

2022-11-08 08:58 UTC, awais-ansari commented on src/discussions/posts/post/PostHeader.jsx
> +                  <span className="container-mw-md text-truncate"> {` / ${topic.name}`} {' '}</span>
spacing nit:
`<span className="container-mw-md text-truncate">{`${getTopicCategoryName(topic)}`}</span>`
`<span>{` / `}</span> or <span className="mx-1">{`/`}</span>`
`<span className="container-mw-md text-truncate">{`${topic.name}`}</span>`

2022-11-14 12:26 UTC, awais-ansari approved these changes

2022-11-14 12:43 UTC, merged