fix: Icons for responses to endorse and mark as answered added
openedx/frontend-app-discussions pull request #346
Opened 2022-11-11 09:27 UTC by ayesha-waris

### [INF-626](https://2u-internal.atlassian.net/browse/INF-626)

- On the unendorsed and unanswered posts, the button is added to endorse or mark as answer.

- The icon when a post is endorsed/or marked answered is made clickable. Clicking would unendorse or unmark as answered.

- In the menu, the icons match endorse/answer icons.

- The menu item “Mark as Answered” is changed to “Mark as answered”.

- The username text color changed to white on the “endorsed” and “answered” statuses.

**Before**

![626](https://user-images.githubusercontent.com/73840786/201309511-7318b84f-dda9-4e25-8350-f4e8932468c4.png)

**After**
<img width="767" alt="Screenshot 2022-11-11 at 3 53 35 PM" src="https://user-images.githubusercontent.com/73840786/201325961-bcb1dc3f-60c6-4263-87b0-fd1f29c4bf64.png">
<img width="1181" alt="Screenshot 2022-11-18 at 6 44 01 PM" src="https://user-images.githubusercontent.com/73840786/202718851-ab7c0fe4-8cf9-4ef3-9a75-93e49a43b6a2.png">
<img width="1171" alt="Screenshot 2022-11-18 at 6 44 09 PM" src="https://user-images.githubusercontent.com/73840786/202718864-7a943807-db25-47f2-888a-b088aa5df3d9.png">

2022-11-15 09:55 UTC, mehaknasir approved these changes

2022-11-16 14:07 UTC, awais-ansari requested changes

2022-11-16 14:07 UTC, awais-ansari commented on src/discussions/common/AuthorLabel.jsx
> -          'text-primary-500': !authorLabelMessage && !isRetiredUser,
We are using this component in the post-summary list too. We need this color there. If you do not need this color than you can add some conditions here.

2022-11-16 14:07 UTC, awais-ansari commented on src/discussions/comments/comment/CommentHeader.jsx
> +  const actionIcons = actions.find(({ action }) => action === 'endorsed');
We have multiple actions with the name `endorsed` in the actions list. Find will get the first action. If you need all the action with `endorsed` then you need to change the array function `find` to `filter`.  
Please update the `action === 'endorsed'`  hard-coded string comparison with the already defined constant for endorsed.

2022-11-18 13:49 UTC, awais-ansari requested changes

2022-11-18 13:49 UTC, awais-ansari commented on src/discussions/comments/comment/CommentHeader.jsx
> +  console.log(actionIcons.id, EndorsementStatus.ENDORSED);
please remove the console.log

2022-11-18 13:49 UTC, awais-ansari commented on src/discussions/comments/comment/CommentHeader.jsx
> +        </span>
Move this span under `actionIcons` condition.

2022-11-18 13:59 UTC, awais-ansari requested changes

2022-11-18 13:59 UTC, awais-ansari commented on src/discussions/comments/comment/CommentHeader.jsx
> +              className={(actionIcons.id === 'endorse' || actionIcons.id === 'unendorse') ? 'text-dark-500' : 'text-success'}
It can be change with this. Please confirm the colors with figma
['endorse', 'unendorse'].includes.(actionIcons.id))

2022-11-21 08:42 UTC, awais-ansari approved these changes

2022-11-21 08:43 UTC, merged