fix: handled thread not found result on frontend
openedx/frontend-app-discussions pull request #360
Opened 2022-11-24 10:12 UTC by mehaknasir

[INF-669](https://2u-internal.atlassian.net/browse/INF-669)

Related Backend Change: https://github.com/openedx/edx-platform/pull/31340 

Focus on the IDs of the thread and course in the screenshot to understand the fix:

original course with thread 
<img width="1680" alt="Screen Shot 2022-11-24 at 3 08 12 PM" src="https://user-images.githubusercontent.com/67791278/203756943-739f563e-c00a-46f0-bcfe-29378fe6c4ef.png">

course trying to fetch a thread that does not belong to it
<img width="1680" alt="Screen Shot 2022-11-24 at 3 07 39 PM" src="https://user-images.githubusercontent.com/67791278/203757049-c7375df1-95aa-43ae-b00a-2abd1cb5714d.png">

also handled for the edit use case
<img width="1680" alt="Screen Shot 2022-11-24 at 3 07 56 PM" src="https://user-images.githubusercontent.com/67791278/203757108-fda1a480-86b8-4920-86a8-02a05af0d79b.png">

2022-11-28 13:15 UTC, awais-ansari requested changes

2022-11-29 20:23 UTC, mehaknasir commented on src/discussions/posts/post-editor/PostEditor.jsx
> +    }
it's better to explicitly return only if the condition is met instead of just returning whenever.

2022-11-30 11:31 UTC, ayeshoali approved these changes

2022-11-30 12:51 UTC, awais-ansari approved these changes

2022-12-01 10:44 UTC, merged