fix: add a post/response/comment during active blackout dates fixed for all roles
openedx/frontend-app-discussions pull request #361
Opened 2022-11-25 11:41 UTC by ayeshoali

Add a post/response/comment during active blackout dates fixed for all roles in discussions MFE and discussion xblocks

**Before **
For discussions MFE when blackout dates are active, buttons for adding a post, response, or comment were not visible for some roles.
**After**
For discussions MFE when blackout dates are active, buttons for adding a post, response, or comment are visible for roles as seen below.

- Global staff
- Course staff 
- Course admin
- Disc. admin
- Disc. moderator
- Disc. TA 
- Disc. Group TA

2022-11-27 20:20 UTC, mehaknasir requested changes
code architectural change is required also test case need to be written based on change in use case.

2022-11-27 20:20 UTC, mehaknasir commented on src/discussions/comments/comment/Comment.jsx
> +
this utility function can be changed to custom hook and all selectors then can easily be utilized there and hook will be used at all placed needed to calculate user privilege.

2022-11-27 20:20 UTC, mehaknasir commented on src/discussions/comments/comment/ResponseEditor.jsx
> +
this duplication will be removed when you shift the logic in custom hook

2022-11-27 20:20 UTC, mehaknasir commented on src/discussions/posts/post-actions-bar/PostActionsBar.jsx
> +
same here

2022-11-28 10:39 UTC, awais-ansari requested changes

2022-11-28 10:39 UTC, awais-ansari commented on src/discussions/utils.js
> +}
Move this code into useUserPrivilage hook and refactor it.
return ((isUserAdmin || userHasModerationPrivilages || isUserGroupTA || isCourseAdmin || isCourseStaff) || false )

2022-11-28 10:39 UTC, awais-ansari commented on src/discussions/data/hooks.js
> +};
rename this hook. The current name is confusing. 
like useUserCanAddThreadInBlackoutDate

2022-11-28 11:01 UTC, awais-ansari requested changes

2022-11-28 11:01 UTC, awais-ansari commented on src/discussions/posts/post-actions-bar/PostActionsBar.jsx
> +
You will not need redundant this check after the hook modification.  The hook will simply return a Boolean value.

2022-11-28 12:45 UTC, awais-ansari requested changes
Add test case for this use case.

2022-11-28 12:45 UTC, awais-ansari commented on src/discussions/data/hooks.js
> +};
refactor this condition.

2022-11-30 11:39 UTC, mehaknasir reviewed
Test cases need to be written for the use cases, would be good if you write test cases for the hook and it will be covering all the parts where the hook is used.

2022-12-01 10:45 UTC, awais-ansari requested changes

2022-12-01 10:45 UTC, awais-ansari commented on src/discussions/data/hooks.js
> +  const ifInBlackoutDateRange = inBlackoutDateRange(blackoutDateRange);
Rema the const `ifInBlackoutDateRange` to `IsInBlackoutDateRange`

2022-12-01 10:45 UTC, awais-ansari commented on src/discussions/data/hooks.js
> +  const ifInBlackoutDateRange = inBlackoutDateRange(blackoutDateRange);
date T, Role T => Add T
date F, Role T => Add T
date T, Role F => Add F
date F, Role F => Add T

!T || T => T
!F || T => T 
!T || F => F 
!F || F => T


!(InBlackoutDateRange) ||
(isUserAdmin || userHasModerationPrivilages || isUserGroupTA || isCourseAdmin || isCourseStaff)

2022-12-01 16:23 UTC, mehaknasir requested changes

2022-12-01 16:23 UTC, mehaknasir commented on src/discussions/data/hooks.test.jsx
> +  });
1. remove beforeEach from each test function as it contains only 1 test case.
2. remove async keyword from beforeEach function
3. structural changes

` describe('blackout dates are active', () => {
      beforeEach(async () => {
        store = initializeStore({
          config: {
            blackouts: [{ start: '2022-11-25T00:00:00Z', end: '2050-11-25T23:59:00Z' }],
            hasModerationPrivileges: false,
            isGroupTa: false,
            isCourseAdmin: false,
            isCourseStaff: false,
            isUserAdmin: false,
          },
        });
      });

      test('return false when blackout dates are active and Role is Learner', async () => {
        const { queryByText } = renderComponent();
        expect(queryByText('false')).toBeInTheDocument();
      });
       test('return false when blackout dates are active and Role is other than', async () => {
        const { queryByText } = renderComponent();
        expect(queryByText('false')).toBeInTheDocument();
      });
    });`


` describe('blackout dates are inActive', () => {
      beforeEach(async () => {
        store = initializeStore({
          config: {
            blackouts: [{ start: '2022-11-25T00:00:00Z', end: '2050-11-25T23:59:00Z' }],
            hasModerationPrivileges: false,
            isGroupTa: false,
            isCourseAdmin: false,
            isCourseStaff: false,
            isUserAdmin: false,
          },
        });
      });

      test('return {{true}} when blackout dates are active and Role is Learner', async () => {
       
      });
       test('return {{true}} when blackout dates are active and Role is not Learner', async () => {
       
      });
    });`

2022-12-02 11:30 UTC, awais-ansari reviewed
I agree with @mehaknasir concerns. Other than that PR LGTM.

2022-12-02 13:18 UTC, awais-ansari approved these changes

2022-12-02 13:23 UTC, merged