fix: removed side bar incase there are no posts
openedx/frontend-app-discussions pull request #367
Opened 2022-11-30 13:38 UTC by AhtishamShahid

Removed the Sidebar in case there are no posts.

<img width="1412" alt="Screen Shot 2022-11-30 at 12 23 57 PM" src="https://user-images.githubusercontent.com/26253150/204733736-f8b19bc0-e65e-4223-a689-b7008e249bb7.png">

2022-12-01 10:02 UTC, awais-ansari requested changes

2022-12-01 10:02 UTC, awais-ansari commented on src/discussions/data/hooks.js
> +  if ((isViewingTopics || isViewingLearners) && totalThreads > 0) {
@AhtishamShahid This solution is not an optimal solution. This change is breaking things in locations. I checkout your branch on my local machine and this is happing. Please check the video. 
https://www.loom.com/share/27abf0da19424bd38c8daef5673b4a39

2022-12-08 08:22 UTC, awais-ansari requested changes

2022-12-08 08:22 UTC, awais-ansari commented on src/discussions/data/hooks.js
> +  selectPostThreadCount, selectThreadCallStatus,
Test cases are failing and the selector is not found in the relative file. Please attach the before, and after videos.

2022-12-14 12:40 UTC, ayeshoali approved these changes

2022-12-19 06:35 UTC, merged