feat: implements new v3 in-context topics structure
openedx/frontend-app-discussions pull request #371
Opened 2022-12-06 11:16 UTC by awais-ansari

feat: implements new v3 in-context topics structure

2022-12-21 15:46 UTC, mehaknasir requested changes

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/discussions-home/DiscussionSidebar.jsx
> +  console.log('displaySidebar', (enableInContext && !enableInContextSidebar));
remove console statement

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/discussions-home/DiscussionsHome.jsx
> +  const { courseNumber, courseTitle, org } = useSelector((state) => state.courseTabs);
can create selector for these as well

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/discussions-home/DiscussionsHome.jsx
> +  useRedirectToThread(courseId);
whats the use of calling these hooks here?

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/discussions-home/DiscussionsHome.jsx
> +  console.log('enableInContext', enableInContext);
need to be removed

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/TopicPostsView.jsx
> +  console.log('TopicPostsView');
remove

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/TopicPostsView.jsx
> +        />
can discuss logic over call

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/TopicsView.jsx
> +  console.log('TopicsList');
remove

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/TopicsView.jsx
> +  }, []);
can pass courseId in dependency array

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/TopicsView.jsx
> +  console.log('TopicsView');
remove

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/components/EmptyTopics.jsx
> +  console.log('topicThreadCount', topicThreadsCount);
remove

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/data/slices.js
> +      state.status = RequestStatus.DENIED;
in case of failure or denied the data will persist for previous request? can empty when call is inProgress

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/topic-search/TopicSearchResultBar.jsx
> +  console.log('TopicSearchResultBar', TopicSearchResultBar);
remove

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/topic/SectionBaseGroup.jsx
> +  console.log('section', section);
remove

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/in-context-topics/topic/Topic.jsx
> +  console.log('topic', topic);
remove

2022-12-21 15:46 UTC, mehaknasir commented on src/discussions/posts/PostsView.jsx
> +  console.log('PostsView');
remove

2022-12-21 18:02 UTC, awais-ansari commented
@mehaknasir Feature is in progress right now. Your all concerns will be resolved soon.

2022-12-29 14:06 UTC, muhammadadeeltajamul approved these changes

2022-12-29 15:25 UTC, mehaknasir approved these changes
can we attach a ticket for test cases before closing PR? I have reviewed the overall structure, it looks good to me. code involves some logical calculations which cannot be explained with meaningful variable names hence I suggested adding code comments to explain better.

The rest of the PR looks good to me, just some minor nits and changes.

2022-12-29 15:25 UTC, mehaknasir commented on src/discussions/in-context-topics/components/EmptyTopics.jsx
> +      actionText={actionText ? intl.formatMessage(actionText) : null}
```
subTitle={subTitle && intl.formatMessage(subTitle)}
actionText={actionText && intl.formatMessage(actionText)}
```

2022-12-30 08:35 UTC, asadazam93 approved these changes
Great work

2022-12-30 09:59 UTC, awais-ansari commented on src/discussions/data/thunks.js
> +        enable_in_context: config.provider === DiscussionProvider.OPEN_EDX,
The above comment is just for the reviewer's knowledge.

2022-12-30 12:15 UTC, merged