fix: removed no endorsed responses from question type post
openedx/frontend-app-discussions pull request #383
Opened 2022-12-12 13:23 UTC by ayeshoali

[INF-684](https://2u-internal.atlassian.net/browse/INF-684)
If there are no responses that have been marked as answer, the “No endorsed responses” section should not appear. Like in the case of Discussion type post.

**Before:**

![b](https://user-images.githubusercontent.com/73840786/207055322-02a3725b-1357-464a-959b-98349396dece.gif)

**After:**

[73707992-dd6f-4177-86c7-f5ecfefdcfe8.webm](https://user-images.githubusercontent.com/73840786/207055683-55dd9ab7-9b68-43ca-8ea1-3379133bf4b8.webm)

2022-12-13 08:23 UTC, AhtishamShahid approved these changes

2022-12-14 16:11 UTC, awais-ansari requested changes

2022-12-20 12:04 UTC, awais-ansari requested changes

2022-12-20 12:04 UTC, awais-ansari commented on src/discussions/comments/CommentsView.jsx
> +        )}
Please avoid the extra lines for `&&`
{((hasMorePages && isLoading) || !isLoading) && (

2022-12-20 12:19 UTC, mehaknasir approved these changes

2022-12-20 12:39 UTC, awais-ansari approved these changes

2022-12-20 12:42 UTC, merged