feat: added tour for not responded filter
openedx/frontend-app-discussions pull request #406
Opened 2023-01-10 06:24 UTC by AhtishamShahid

2023-01-10 10:42 UTC, awais-ansari requested changes
This PR is related to a specific NotRespondedFilter tour. I'm curious about if we add multiple tours in MFE then what will be the case? 
1.  Would We need to create each separate file for a new tour?
2. Can we make this file generic? such as it will create tours for every tour response.

2023-01-10 10:42 UTC, awais-ansari commented on src/discussions/tours/data/selectors.js
> +  }
This case will never run because you are already find the redux state and redux state will not be undefined or null.

2023-01-10 10:42 UTC, awais-ansari commented on src/discussions/tours/data/selectors.js
> +  const response = tours.tours.find(tour => tour.tourName === 'not_responded_filter');
You can also create a new selector called `selectTours => (state) => state.tours.tours` and use `selectTours` selector in this selector. which is make it cleaner and you can use `selectTours` anywhere to get the tour data.

2023-01-10 10:42 UTC, awais-ansari commented on src/discussions/tours/NotRespondedFilter.jsx
> +        title: 'New filtering option!',
Translations missing.

2023-01-10 10:42 UTC, awais-ansari commented on src/discussions/tours/NotRespondedFilter.jsx
> +        body: 'Now you can filter discussions .',
Translation missing and extra space before `.`

2023-01-10 10:42 UTC, awais-ansari commented on src/discussions/tours/NotRespondedFilter.jsx
> +    enabled: tourData ? tourData.showTour : false,
**Breaking Change**
This check will not work in the case of an empty object and the **code will break**. You are returning an empty object through your selector if the required data does not found. 
`{} ? true : false => output: true`

This check will work when the selector would return the data object or undefine/null.

2023-01-10 10:42 UTC, awais-ansari commented on src/discussions/tours/NotRespondedFilter.jsx
> +    endButtonText: 'Okay',
Translations missing

2023-01-10 10:42 UTC, awais-ansari commented on src/discussions/tours/NotRespondedFilter.jsx
> +export default () => {
Is it an anonymous default function?

2023-01-10 10:42 UTC, awais-ansari commented on src/discussions/discussions-home/DiscussionsHome.jsx
> +        <NotRespondedFilter />
is It necessary to render it here or it can be moved at end?

2023-01-16 08:36 UTC, awais-ansari approved these changes

2023-01-16 08:36 UTC, awais-ansari commented on src/discussions/tours/data/selectors.js
> +};
export const notRespondedFilterTour = createSelector(
  selectTours,
  (tours) => (tours.find(tour => tour.tourName === 'not_responded_filter')),
);

2023-01-16 08:36 UTC, awais-ansari commented on src/discussions/tours/NotRespondedFilter.jsx
> +    enabled: tourData ? tourData.showTour && !enableInContextSidebar : false,
tourData && Boolean(tourData.showTour && !enableInContextSidebar)

2023-01-16 08:36 UTC, awais-ansari commented on src/discussions/tours/NotRespondedFilter.jsx
> +  };
Create a config function in the utile file and move this config there. or you can create a hook for config 
const tourConfig = (intl, dispatch, tour) => 
tour.maps(tour => ({
    tourId: tour.id,
    advanceButtonText: intl.formatMessage(messages.advanceButtonText),
    dismissButtonText: intl.formatMessage(messages.dismissButtonText),
    endButtonText: intl.formatMessage(messages.endButtonText),
    enabled: tour ? tour.showTour && !enableInContextSidebar : false,
    onDismiss: () => dispatch(updateTourShowStatus(tour.id)),
    onEnd: () => dispatch(updateTourShowStatus(tour.id)),
    checkpoints: [
      {
        body: intl.formatMessage(messages[tour.name]),
        placement: 'right',
        target: '#icon-tune',
        title: intl.formatMessage(messages[tour.name]),
      },
    ],
 })

2023-01-17 11:24 UTC, mehaknasir approved these changes

2023-01-17 15:55 UTC, merged