style: post content style updates
openedx/frontend-app-discussions pull request #407
Opened 2023-01-13 11:23 UTC by ayeshoali

[INF-706](https://2u-internal.atlassian.net/browse/INF-706)

UX did some discoveries and created a new layout to increase content density, because of lots of feedback about it.

Mockups can be found here: [Discussions](https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussions?node-id=7332%3A316353&t=QhWkFQjlb50HPqvb-0)

Following are the updates mentioned in the video and Figma:

- Change Post Title line height to 21px and font-size to 14px
- Changed Post Topic size to 12 px
- Moved Post Time next to author name
- Like and Follow Icons only show up when atleast have one like or followed
- On Post/Comment hover/focus shows Hover Action Card including Add Comment/ Add Response, Like,  Follow, Endorsed and ActionDrop Down button
- All Buttons have Light/300 background on hover
- Like and Follow Icons background changed to Light/300 on Hover
- Change Endorsed Alert height to 40px
- Removed "Endorsed Icon" From Comment Card
- Removed "Endorsed by Author" to only AuthorLabel Icon and Author /label and then Endorsed Time
- In Endorsed Alert AuthorLabel and Icon shows tooltips with author name
- Changed Height of Comment and Reply Card according to Figma
- Changed Height of "Showing n Responses"

<img width="1199" alt="Screenshot 2023-01-13 at 4 15 18 PM" src="https://user-images.githubusercontent.com/73840786/212307894-deb00c5a-0647-41ca-9365-e92ae3bb9b0d.png">
<img width="1185" alt="Screenshot 2023-01-13 at 4 15 30 PM" src="https://user-images.githubusercontent.com/73840786/212307910-05019f8a-15da-4f06-a291-ff8418496003.png">
<img width="1197" alt="Screenshot 2023-01-13 at 4 15 37 PM" src="https://user-images.githubusercontent.com/73840786/212307915-e2fa87ae-5d9e-48d8-9e61-130262662c1a.png">
<img width="1188" alt="Screenshot 2023-01-13 at 4 15 45 PM" src="https://user-images.githubusercontent.com/73840786/212307917-7b6888ed-c303-475b-82c2-a29f11c89191.png">
<img width="1176" alt="Screenshot 2023-01-13 at 4 16 01 PM" src="https://user-images.githubusercontent.com/73840786/212307918-588178c3-28fc-4a80-8fa7-907593bfb8e3.png">
<img width="1167" alt="Screenshot 2023-01-13 at 4 16 07 PM" src="https://user-images.githubusercontent.com/73840786/212307921-30696f99-a176-449f-b35c-8a286a5103be.png">
<img width="1212" alt="Screenshot 2023-01-13 at 4 16 23 PM" src="https://user-images.githubusercontent.com/73840786/212307925-6f8a6360-93f7-4d4e-9f8c-5988de8a01f9.png">

2023-01-16 11:05 UTC, mehaknasir requested changes
This PR can be improved by adding test coverage for hovercard

1. when it should be visible
2. when it should be hidden
3. which elements should be visible within hovercard 
4. add test cases for post header, time stamp, post title, etc

there are some custom classes made that I believe can be picked from paragon

2023-01-16 11:14 UTC, ayeshoali commented on src/discussions/comments/CommentsView.jsx
> +            lineHeight: '24px',
default lineHeight = 18.664

2023-01-16 11:17 UTC, ayeshoali commented on src/discussions/comments/comment/Comment.jsx
> +              }}
default lineHeight = 18.664px

2023-01-16 17:06 UTC, awais-ansari requested changes
There are many changes in implementation as compared to Figma. Few of those are
<img width="617" alt="Screenshot 2023-01-16 at 9 52 35 PM" src="https://user-images.githubusercontent.com/79941147/212732759-431b6ee7-2fa2-4b41-9040-a825510835b5.png">
<img width="535" alt="Screenshot 2023-01-16 at 9 52 44 PM" src="https://user-images.githubusercontent.com/79941147/212732769-02201a63-5dab-438a-96db-deacd1bd9413.png">
<img width="1118" alt="Screenshot 2023-01-16 at 10 00 08 PM" src="https://user-images.githubusercontent.com/79941147/212732773-e9685755-b5f2-491c-b2b5-88e4a2893eb0.png">
<img width="937" alt="Screenshot 2023-01-16 at 10 00 25 PM" src="https://user-images.githubusercontent.com/79941147/212732779-b125098f-5edf-4e85-bcfc-e985d5a32da1.png">
<img width="943" alt="Screenshot 2023-01-16 at 10 03 53 PM" src="https://user-images.githubusercontent.com/79941147/212732783-0d787f9f-a4ec-4d9b-8667-37e51d945fb6.png">
<img width="786" alt="Screenshot 2023-01-16 at 10 04 00 PM" src="https://user-images.githubusercontent.com/79941147/212732785-1134783e-d8d0-4b8c-8516-3ef499a91e5c.png">

2023-01-16 17:07 UTC, awais-ansari reviewed
@ayeshoali please compare UI changes with Figma in detail. Thanks!

2023-01-27 11:45 UTC, mehaknasir requested changes

2023-01-27 11:45 UTC, mehaknasir commented on src/discussions/comments/comment/Reply.jsx
> +          <div className="d-flex flex-row justify-content-between" style={{ height: '24px' }}>
height: 24px?

2023-01-27 11:45 UTC, mehaknasir commented on src/discussions/comments/comment/ResponseEditor.jsx
> +  // const [addingResponse, setAddingResponse] = useState(false);
nit: remove commented code

2023-01-27 11:45 UTC, mehaknasir commented on src/discussions/common/HoverCard.jsx
> +      {endorseIcons !== undefined && (
`{endorseIcons && (`

simplifying this would not work?

2023-01-27 11:45 UTC, mehaknasir commented on src/discussions/common/HoverCard.jsx
> +      {commentOrPost.following !== undefined && (
`{commentOrPost.following  && (`

2023-01-27 11:45 UTC, mehaknasir commented on src/discussions/common/HoverCard.jsx
> +  endorseIcons: undefined,
why pass the default as undefined? if that won't be passed in props they still are undefined?

2023-01-27 11:45 UTC, mehaknasir commented on src/index.scss
indents needs to be fixed

2023-01-27 11:45 UTC, mehaknasir commented on src/index.scss
>  }
indents needs to be fixed

2023-01-27 11:45 UTC, mehaknasir commented on src/index.scss
> +  ;
indents needs to be fixed

2023-01-27 14:34 UTC, mehaknasir approved these changes

2023-01-27 14:43 UTC, mehaknasir commented on src/discussions/common/HoverCard.jsx
> +      {commentOrPost.following !== undefined && (
I have found test cases fails if that condition is removed

2023-01-30 09:50 UTC, asadazam93 approved these changes
please squash the commits before merging

2023-01-30 12:07 UTC, awais-ansari approved these changes

2023-01-30 12:08 UTC, awais-ansari reviewed
These changes are just code clean-up and refactoring. You can create a new ticket for it and merge this PR.

2023-01-30 12:30 UTC, merged