fix: use threads api in case of search
openedx/frontend-app-discussions pull request #419
Opened 2023-01-26 06:25 UTC by AhtishamShahid

2023-01-27 14:41 UTC, mehaknasir approved these changes

2023-01-31 13:04 UTC, awais-ansari requested changes

2023-01-31 13:04 UTC, awais-ansari commented on src/discussions/posts/PostsList.jsx
> +    }
This part of the condition `(prevFilters.current.search !== '' && prevFilters.current.search !== filters.search)` would be false always. `prevFilters` is initialized with an empty string and does not change after that. So its value remains an empty string and this check `prevFilters.current.search !== ''` will get false. 
Indirectly,  Your check only depends on `!showOwnPosts`. The previous code was working on the same logic. However, current change is not required.

2023-02-01 09:02 UTC, awais-ansari approved these changes

2023-02-01 09:17 UTC, merged