style:  in-context discussions style updates
openedx/frontend-app-discussions pull request #426
Opened 2023-02-03 14:56 UTC by ayeshoali

[INF-740](https://2u-internal.atlassian.net/browse/INF-740)
UX did some discoveries and created a new layout to increase content density, because of lots of feedback about it.

Mockups can be found here: [Discussions](https://www.figma.com/file/LVFnO9oRHYiamoicZuXDAC/Discussions?node-id=7332%3A316353&t=QhWkFQjlb50HPqvb-0)

Following are the updates mentioned  and Figma:
<img width="521" alt="Screenshot 2023-02-03 at 7 49 43 PM" src="https://user-images.githubusercontent.com/73840786/216634547-fb355af8-e614-417f-a0dd-048e0bcda337.png">
<img width="527" alt="Screenshot 2023-02-03 at 7 50 03 PM" src="https://user-images.githubusercontent.com/73840786/216634561-4d5fda78-5a7c-4185-a286-e7f0e9ff0dca.png">
<img width="530" alt="Screenshot 2023-02-03 at 7 50 13 PM" src="https://user-images.githubusercontent.com/73840786/216634569-70b4159f-5608-4517-8939-a04521df5e0a.png">
<img width="512" alt="Screenshot 2023-02-03 at 7 50 23 PM" src="https://user-images.githubusercontent.com/73840786/216634572-08b5fc8b-9652-4a23-8ea3-fb41aa786209.png">

2023-02-06 15:08 UTC, awais-ansari requested changes

2023-02-06 15:08 UTC, awais-ansari commented on src/discussions/posts/post/PostLink.jsx
> +                  />
fix the alignment. classNames length should be less then 121 character.

2023-02-06 15:08 UTC, awais-ansari commented on src/discussions/posts/post/PostSummaryFooter.jsx
> +          <span className="sr-only">{' '}{intl.formatMessage(post.following ? messages.srOnlyFollowDescription : messages.srOnlyUnFollowDescription)}</span>
fix the alignment. classNames length should be less than 121 characters.

2023-02-06 15:08 UTC, awais-ansari commented on src/index.scss
> +    ;
extra spacing

2023-02-06 15:08 UTC, awais-ansari commented on src/index.scss
> +  ;
extra spacing

2023-02-06 15:08 UTC, awais-ansari commented on src/index.scss
> +    ;
extra spacing

2023-02-06 15:08 UTC, awais-ansari commented on src/index.scss
> +  ;
extra spacing

2023-02-06 15:08 UTC, awais-ansari commented on src/index.scss
> +  ;
extra spacing

2023-02-06 15:08 UTC, awais-ansari commented on src/index.scss
>  }
extra spacing

2023-02-07 10:18 UTC, ayeshoali commented on src/discussions/comments/CommentsView.jsx
> +        className="discussion-comments d-flex flex-column card border-0 post-card-margin post-card-padding"
@mehaknasir  yes, I have checked when not in-context.
@awais-ansari , post content UI change was not rendering in in-context, this only implants change in in-context

2023-02-07 12:37 UTC, awais-ansari approved these changes

2023-02-07 12:37 UTC, awais-ansari commented on src/discussions/comments/CommentsView.jsx
> +                style={{ lineHeight: '24px' }}
create a class and use it because this inline style is using multiple places.

2023-02-07 12:37 UTC, awais-ansari commented on src/discussions/posts/post-actions-bar/PostActionsBar.jsx
> +            className={classNames('my-0 font-style', { 'px-3 py-10px border-0': enableInContextSidebar })}
{classNames('my-0 font-style border-0', { 'px-3 py-10px': enableInContextSidebar })}

remove border: '0px' class from inline style

2023-02-09 09:41 UTC, mehaknasir approved these changes

2023-02-09 09:42 UTC, mehaknasir commented
Squash your commits before merge

2023-02-09 11:08 UTC, merged