fix: fix mathjax text overflowing
openedx/frontend-app-discussions pull request #429
Opened 2023-02-06 13:17 UTC by ayeshoali

[INF-759](https://2u-internal.atlassian.net/browse/INF-759)
Text was overflowing on this for mathjax content.

**Before**
<img width="1191" alt="Screenshot 2023-02-06 at 6 16 34 PM" src="https://user-images.githubusercontent.com/73840786/216981171-3d66e312-f54d-43bd-b22f-e9df034a890a.png">

**After**
<img width="1174" alt="Screenshot 2023-02-06 at 6 16 42 PM" src="https://user-images.githubusercontent.com/73840786/216981184-c9e450cd-0dd2-41a1-967c-a2db5d6203b7.png">

2023-02-06 14:15 UTC, awais-ansari approved these changes

2023-02-06 14:15 UTC, awais-ansari commented on src/index.scss
> +  ;
why is there a lot of space?

2023-02-06 14:15 UTC, awais-ansari commented on src/index.scss
> +  ;
why is there a lot of space?

2023-02-06 15:40 UTC, mehaknasir requested changes
the indentation needs to be fixed

2023-02-07 15:02 UTC, mehaknasir approved these changes

2023-02-08 10:17 UTC, merged