added redux, api and selector test cases for in context topics
openedx/frontend-app-discussions pull request #430
Opened 2023-02-09 11:42 UTC by sundasnoreen12

### Description
Added test cases for redux store manipulation, API responses, and selectors
https://2u-internal.atlassian.net/browse/INF-725

#### How Has This Been Tested?
I tested my changes by running the command "npm run test [relative path of the file]

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2023-02-09 12:00 UTC, mehaknasir requested changes
Good work with the code structuring and details, can you please look into thee points I have added.

2023-02-09 18:19 UTC, awais-ansari requested changes
I'm searching for the best practice for test cases and I find out no one is using selectors directly in test cases. It is happing because selectors would be tested on component integration testing. 
https://www.xtivia.com/blog/best-practices-for-testing-a-react-redux-toolkit-app/
https://www.willowtreeapps.com/craft/best-practices-for-unit-testing-with-a-react-redux-approach

2023-02-10 13:52 UTC, awais-ansari requested changes
Just small changes. Other than that LGTM.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/__factories__/inContextTopics.factory.js
> +    });
line width is greater than 120. Please split this line into multiple lines.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/__factories__/inContextTopics.factory.js
> +  .sequence('lms_web_url', ['id', 'courseId'], (idx, id, courseId) => `${getApiBaseUrl}/courses/${courseId}/jump_to/block-v1:${id}`)
These lines have width greater than 120. split these lines into multiple lines.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/__factories__/inContextTopics.factory.js
> +    });
These lines have a width greater than 120. split these lines into multiple lines.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/__factories__/inContextTopics.factory.js
> +  });
allow this attribute to get dynamic params for discussion count and question count.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/__factories__/inContextTopics.factory.js
> +  .sequence('student_view_url', ['id', 'courseId'], (idx, id, courseId) => `${getApiBaseUrl}/xblock/${courseId.replace('course-v1:', 'block-v1:')}+type@chapter+block@${id}`)
These lines have a width greater than 120. split these lines into multiple lines.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/__factories__/inContextTopics.factory.js
> +    });
These lines have width greater than 120. split these lines into multiple lines.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/__factories__/inContextTopics.factory.js
> +    });
pass discussion and question count values from here.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/api.test.js
> +        topicPrefix: 'noncourseware-topic', enabledInContext: true, topicNamePrefix: 'general-topic', usageKey: '', courseware: false,
These lines have width greater than 120. split these lines into multiple lines.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/redux.test.js
> +        topicPrefix: 'noncourseware-topic', enabledInContext: true, topicNamePrefix: 'general-topic', usageKey: '', courseware: false,
These lines have width greater than 120. split these lines into multiple lines.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/selector.test.jsx
> +        topicPrefix: 'noncourseware-topic', enabledInContext: true, topicNamePrefix: 'general-topic', usageKey: '', courseware: false,
These lines have width greater than 120. split these lines into multiple lines.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/topics/data/__factories__/topics.factory.js
> -    discussion: 0,
I think this is removed by mistake.

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/selectors.js
> +
we still need this selector?

2023-02-10 13:52 UTC, awais-ansari commented on src/discussions/in-context-topics/data/selector.test.jsx
> +        .toBeUndefined();
make it one line

2023-02-10 16:11 UTC, awais-ansari approved these changes
LGTM

2023-02-13 07:31 UTC, muhammadadeeltajamul approved these changes

2023-02-13 11:03 UTC, mehaknasir approved these changes

2023-02-13 11:37 UTC, merged