feat: added stats at subsection level in topics tab
openedx/frontend-app-discussions pull request #437
Opened 2023-02-15 12:32 UTC by muhammadadeeltajamul

### Description

Added stats at sub-section level in topics tab.

Ticket: [INF-763](https://2u-internal.atlassian.net/browse/INF-763)

#### How Has This Been Tested?

Open Topics tab in discussions mfe. Stats will be visible for courseware topics

#### Visual Change Screenshots
Before
![inf-763_before](https://user-images.githubusercontent.com/77053848/219301393-8762a173-696b-44d5-a1a3-079e6389e061.png)

After
![inf-763_after](https://user-images.githubusercontent.com/77053848/219301444-a43ebec5-cffc-4bc8-a60d-e686547b7429.png)

#### Merge Checklist

* [x] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [x] Is there adequate test coverage for your changes?

2023-02-15 13:27 UTC, mehaknasir commented
Can we add test cases for new components please?

2023-02-16 06:30 UTC, muhammadadeeltajamul commented
Test cases for v3 topics are in progress in another ticket

2023-02-16 06:48 UTC, awais-ansari requested changes
Add a proper description, and before, and after screenshots for better visibility.

2023-02-16 06:48 UTC, awais-ansari commented on src/data/constants.js
> +});
`topicShape` is not a constant. Move this to the relevant component and then export from there.

2023-02-16 07:58 UTC, mehaknasir approved these changes

2023-02-16 12:48 UTC, awais-ansari approved these changes
LGTM

2023-02-17 03:29 UTC, merged