test: added testcases of redux, selector and api
openedx/frontend-app-discussions pull request #459
Opened 2023-03-01 11:04 UTC by sundasnoreen12

INF-793
### Description

https://2u-internal.atlassian.net/browse/INF-793

Add test cases for redux store manipulation, API responses, selector, and important Util functions.

1. API responses
       a. Successfully get API response for the learner's list(learners profile) and learners posts(threads)
       b. Successfully store learners and learnerPosts API data in redux
       c. Failed to fetch learners
       d. Failed to fetch learner posts
       e. denied to fetch learners
       f. denied to fetch learner posts

2. Learners redux store 
      a. Successfully load initial states in redux
      b. Successfully store a learner posts stats data as pages object in redux
      c. Successfully store the nextPage, totalPages, totalLearners, and sortedBy data in redux
      d. Successfully update the learner's sort data in redux when selecting a different sort other than the default
      e. Successfully update the post-filter data in redux when selecting a different post-filter other than the default
      f. Successfully update the learner's search query in redux when searching for a learner

3. Selectors
      a. learnersLoadingStatusshould return learners list loading status
      b. selectUsernameSearch should return a learner search query 
      c. selectLearnerSorting should return learner sortedBy
      d. selectLearnerNextPage should return learners next page

#### How Has This Been Tested?

I tested this by running the npm command "npm run test"

#### Merge Checklist

* [ ✅] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2023-03-01 14:31 UTC, awais-ansari requested changes
please check the codecov report and cover the possible uncovered lines of code.

2023-03-01 14:31 UTC, awais-ansari commented on src/discussions/learners/data/api.test.jsx
> +    const apiUrl = `${coursesApiUrl}${learnerCourseId}/learner/`;
create an export function for learnerPostsApi in thunk file and export here.

2023-03-01 14:31 UTC, awais-ansari commented on src/discussions/learners/data/api.test.jsx
> +      .reply(() => [statusCode, learnersData]);
Please confirm the can we get the status code from the thunk call without explicitly passing here. e.g
axiosMock.onGet(`${coursesApiUrl}${learnerCourseId}/activity_stats/`).reply(200, {learnersData});

2023-03-01 14:31 UTC, awais-ansari commented on src/discussions/learners/data/api.test.jsx
> +    expect(learners.learnerProfiles).not.toBeUndefined();
Explicitly check the length because undefined !== [].
expect(learners.learnerProfiles).toEqual(3);

2023-03-01 14:31 UTC, awais-ansari commented on src/discussions/learners/data/api.test.jsx
> +    expect(threads.threadsById).not.toBeUndefined();
Explicitly check the length because undefined !== [].
expect(learners.learnerProfiles).toEqual(3);

2023-03-01 14:31 UTC, awais-ansari commented on src/discussions/learners/data/redux.test.jsx
> +      const pages = learners.pages[0];
rename to page.

2023-03-01 14:31 UTC, awais-ansari commented on src/discussions/learners/data/redux.test.jsx
> +      const stats = pages[0];
rename to `statsObject`

2023-03-02 11:26 UTC, awais-ansari requested changes

2023-03-02 11:26 UTC, awais-ansari commented on src/discussions/learners/data/api.test.jsx
> +    await executeThunk(fetchUserPosts(courseId, { filters: { status: 'statusUnanswered' } }), store.dispatch, store.getState);
line length is exceeding form 120 characters.

2023-03-02 11:26 UTC, awais-ansari commented on src/discussions/learners/data/api.test.jsx
> +    await executeThunk(fetchUserPosts(courseId, { filters: { status: 'all' } }), store.dispatch, store.getState);
is there any reason to execute an API call with different filter values?

2023-03-02 11:26 UTC, awais-ansari commented on src/discussions/learners/data/api.test.jsx
> +  });
You already test this case in the above test case.  So there's no need to explicitly test this scenario. You can remove this test case and update the above test case description.

2023-03-03 09:20 UTC, awais-ansari requested changes
Just a small nit. other than that LGTM.

2023-03-03 09:20 UTC, awais-ansari commented on src/discussions/learners/data/api.test.jsx
> +  ])('Successfully fetch user posts based on multiple filters', async ({ status, search, cohort }) => {
add dynamic status value test statements like this.
'Successfully fetch user posts based on ${status} and ${seacrch} and ${cohort} filters.

2023-03-03 11:27 UTC, awais-ansari approved these changes
@sundasnoreen12 please rebase this PR before merging.

2023-03-03 13:42 UTC, ayeshoali requested changes

2023-03-03 13:42 UTC, ayeshoali commented on src/discussions/learners/data/api.test.jsx
> +  }
The same method is repeated in the redux.test.jsx and selector.test.jsx, please check if it can be exported from one file.

2023-03-08 04:16 UTC, muhammadadeeltajamul approved these changes

2023-03-08 08:37 UTC, ayeshoali approved these changes

2023-03-08 09:25 UTC, merged