added new test cases for learners and posts
openedx/frontend-app-discussions pull request #470
Opened 2023-03-15 09:35 UTC by sundasnoreen12

[INF-811](https://2u-internal.atlassian.net/browse/INF-811)
### Description

Add test cases for the following cases.

1. Selector
    a. Need to remove selectLearnerLastLogin and selectLearner selectors because these selectors are not using in any 
        component.

2. Factory
    a. It should display learners based on condition activeFlags <= len 

3. LearnerCard
    a. It should create a post with the logged in user name to meet this condition (learner.username === learnerUsername)

4. LearnerFilterBar
     a. It should filter the learner’s list based on sort-reported filter

5. LearnerFooter
    a. It should display reported message by passing activeFlags or inactiveFlags in the factory of leaner.
    b. It should display previouslyReported message by passing activeFlags or inactiveFlags in the factory of leaner.

6. LearnerPostFilterbar
    a. It should filter the learner’s posts based on cohort.
    b. It should fetch course cohorts by enabling userHasModerationPrivileges flag.

7. LearnerPostsView
    a. It should display load more posts button
    b. It should display more posts by clicking on load more posts button.

8. LearnersView
    a. It should redirect to Post tab by pass false value to learnersTabEnabled flag.
    b. It should display load more button
    c. It should display more learners by clicking on load more button.
    d. It should call fetchLearners by enabling nextPage as true.

#### How Has This Been Tested?
npm run test 

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [✅] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2023-03-15 13:08 UTC, awais-ansari requested changes

2023-03-15 13:08 UTC, awais-ansari commented on src/discussions/learners/LearnerPostsView.test.jsx
> +    const loadMoreButton = container.querySelector('[data-testid="load-more"]');
- wrap the waitFor(()=> (container.querySelector('[data-testid="load-more"]'))
- Remove waitFor from renderComponent();

2023-03-15 13:08 UTC, awais-ansari commented on src/discussions/learners/LearnersView.test.jsx
> +      });
Remove waitFor

2023-03-15 15:48 UTC, awais-ansari approved these changes

2023-03-16 09:02 UTC, ayeshoali requested changes

2023-03-16 09:02 UTC, ayeshoali commented on src/discussions/learners/LearnersView.test.jsx
> +
remove extra line here

2023-03-16 09:02 UTC, ayeshoali commented on src/discussions/learners/LearnersView.test.jsx
> +    const loadMoreButton = container.querySelector('[data-testid="load-more"]');
repetition of query here, this can be changed to const loadMoreButton = await container.querySelector('[data-testid="load-more"]');

2023-03-16 09:43 UTC, ayeshoali approved these changes

2023-03-16 09:48 UTC, merged