fix: removes outline around comment cards (#487)
openedx/frontend-app-discussions pull request #489
Opened 2023-03-30 07:27 UTC by sundasnoreen12

[INF-343](https://2u-internal.atlassian.net/browse/INF-343)
### Description

Add units tests for all the components that are added for course navigation bar.
Test that the course navigation bar has the correct urls for all the other tabs.
Test that the discussions tab shows the discussions MFE

#### How Has This Been Tested?
npm run test 

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2023-03-31 07:55 UTC, awais-ansari requested changes

2023-03-31 07:55 UTC, awais-ansari commented on src/components/NavigationBar/data/__factories__/navigationBar.factory.js
> +  .sequence('course_id', (idx) => `course-v1-${idx}`)
make it `option` with a default value of `course-v1:edX+DemoX+Demo_Course`.

2023-03-31 07:55 UTC, awais-ansari commented on src/components/NavigationBar/data/__factories__/navigationBar.factory.js
> +  .option('courseId', null, 'course-v1:edX+DemoX+Demo_Course')
You can use `course_id`. No need to define `courseId` again

2023-03-31 07:55 UTC, awais-ansari commented on src/components/NavigationBar/data/thunks.js
> -      if (!courseHomeCourseMetadata.courseAccess.hasAccess) {
This condition is required to check the Access permission.

2023-03-31 07:55 UTC, awais-ansari commented on src/components/NavigationBar/data/api.test.js
> +
remove extra line

2023-03-31 07:55 UTC, awais-ansari commented on src/components/NavigationBar/data/api.test.js
> +  it('successfully get navigation tabs', async () => {
The first character should be capital. Successfully

2023-04-04 07:02 UTC, awais-ansari approved these changes

2023-04-04 07:02 UTC, awais-ansari commented on src/components/NavigationBar/data/__factories__/navigationBar.factory.js
> +
remove extra line

2023-04-04 09:40 UTC, ayeshoali commented on src/components/NavigationBar/data/api.test.js
> +    expect(store.getState().courseTabs.courseStatus).toEqual('loaded');
I believe courseStatus should be checked before tabs

2023-04-04 11:12 UTC, ayeshoali approved these changes
Please rebase before merging

2023-04-04 11:22 UTC, merged