Sundas/inf 818
openedx/frontend-app-discussions pull request #498
Opened 2023-04-14 10:56 UTC by sundasnoreen12

[INF-818](https://2u-internal.atlassian.net/browse/INF-818)
### Description

1. Role info needs to be present in edited and closed banner.
2. Username and role color in the banner should match figma.

|Before|After|
|-------|-----|
|      |      |

**Before**

<img width="562" alt="Screenshot 2023-04-14 at 3 54 29 PM" src="https://user-images.githubusercontent.com/72802712/232026106-d56575d1-5eb4-4c0e-8ac5-ab51ea13b7cf.png">

**After**

<img width="653" alt="Screenshot 2023-04-14 at 3 54 49 PM" src="https://user-images.githubusercontent.com/72802712/232026163-13a91e4e-e2ea-470c-ad27-294ae0fb89c0.png">

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2023-04-14 11:29 UTC, awais-ansari approved these changes

2023-04-17 09:23 UTC, AhtishamShahid approved these changes

2023-04-17 10:00 UTC, ayesha-waris requested changes

2023-04-17 10:00 UTC, ayesha-waris commented on src/discussions/common/AuthorLabel.jsx
> +              className={classNames('font-size-14 font-style font-weight-500', {
Please review if removing mr-1.5 has side effects at other places where it's been used

2023-04-17 12:03 UTC, ayesha-waris commented on src/discussions/common/AlertBanner.jsx
> +
Nit
please remove this extra line

2023-04-19 10:58 UTC, merged