fix: action dropdown UI issues
openedx/frontend-app-discussions pull request #500
Opened 2023-04-18 07:50 UTC by sundasnoreen12

[INF-848](https://2u-internal.atlassian.net/browse/INF-848)
### Description

Response sort modal popup is displayed above the actions dropdown menu because the z-index is same for both.

AC:

1. Actions Dropdown should be above response sort menu
2. Check if actions dropdown menu is above the header (for mobile view)
3. Make sure response sort popup is also responding in correct order (for mobile view)

#### Screenshots:
|Before|After|
|-------|-----|
|<img width="410" alt="Screenshot 2023-04-18 at 12 49 22 PM" src="https://user-images.githubusercontent.com/72802712/232708961-1df70bcf-3e97-4b9d-807c-ecd36652855d.png">|<img width="360" alt="Screenshot 2023-04-18 at 12 49 46 PM" src="https://user-images.githubusercontent.com/72802712/232709043-20492177-1402-42ee-b3d0-118f62c9269b.png">|

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2023-04-18 08:34 UTC, AhtishamShahid approved these changes

2023-04-18 08:56 UTC, ayesha-waris requested changes

2023-04-18 09:02 UTC, ayesha-waris commented on src/index.scss
> +  background-color: #fff;
why the change of background colour?

2023-04-18 09:47 UTC, ayesha-waris approved these changes

2023-04-18 14:39 UTC, awais-ansari commented on src/index.scss
> -  z-index: 1;
After removing the z-index. Please check the comment sort dropdown is clickable or not.

2023-04-20 11:29 UTC, awais-ansari approved these changes

2023-04-20 12:05 UTC, merged