feat: integrated backend discussions restriction with MFE
openedx/frontend-app-discussions pull request #529
Opened 2023-05-30 09:55 UTC by ayesha-waris

[INF-828](https://2u-internal.atlassian.net/browse/INF-828)
### Description

Integrated already build UI with the API change in [INF-826](https://2u-internal.atlassian.net/browse/INF-826)

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2023-05-31 09:59 UTC, awais-ansari requested changes

2023-05-31 09:59 UTC, awais-ansari commented on src/discussions/data/hooks.js
> +  return (isPostingEnabled || (isPrivileged));
(isPostingEnabled || isPrivileged)

2023-05-31 09:59 UTC, awais-ansari commented on src/discussions/data/hooks.js
> +export const useUserCanAddThreadInPostingRestriction = () => {
useUserCanAddThreadInPostingRestriction => useUserPostingEnabled

2023-05-31 09:59 UTC, awais-ansari commented on src/discussions/discussions-home/BlackoutInformationBanner.jsx
>  const BlackoutInformationBanner = () => {
change the name of function or anywhere we area using blockoutDates.

2023-05-31 09:59 UTC, awais-ansari commented on src/discussions/discussions-home/BlackoutInformationBanner.jsx
> +  const isDiscussionsBlackout = !useSelector(selectIsPostingEnabled);
IsPostingEnabled =  useSelector(selectIsPostingEnabled);

2023-05-31 09:59 UTC, awais-ansari commented on src/discussions/data/slices.js
> +    isPostingEnabled: true,
make it false.

2023-05-31 09:59 UTC, awais-ansari commented on src/discussions/discussions-home/BlackoutInformationBanner.test.jsx
> +  ])('Test Blackout Banner is visible on app load if posting is disabled', async ({ isPostingEnabled, visibility }) => {
update the description

2023-05-31 09:59 UTC, awais-ansari commented on src/discussions/common/ActionsDropdown.jsx
> +  // Find and remove edit action if in Posting restriction date range or postimg is disabled.
update the description

2023-06-05 13:01 UTC, awais-ansari approved these changes

2023-06-06 08:11 UTC, sundasnoreen12 approved these changes

2023-06-06 09:18 UTC, merged