feat: upgrade react router to v6
openedx/frontend-app-discussions pull request #542
Opened 2023-06-20 04:42 UTC by Syed-Ali-Abbas-Zaidi

### Description

This PR upgrades `react-router-dom` from `v5` to `v6`.

2023-10-24 09:53 UTC, awais-ansari commented
Hi @Syed-Ali-Abbas-Zaidi, Just to confirm. Are you still working on this PR? We are planning the board cleanup. Should I close this PR?

2023-10-24 10:12 UTC, Syed-Ali-Abbas-Zaidi commented
> Hi @Syed-Ali-Abbas-Zaidi, Just to confirm. Are you still working on this PR? We are planning the board cleanup. Should I close this PR?

Hi, This PR is currently blocked due to this [issue in react-router v6](https://github.com/remix-run/react-router/pull/10768). This issue was resolved last week but it will be released in a week or two and after that, we will start working on this PR.

2023-11-01 11:35 UTC, awais-ansari commented
@Syed-Ali-Abbas-Zaidi We are doing some optimization work and decomposition of tightly coupled components to prevent unwanted re-rendering. This PR will be affected by that work. We need to add a little bit of delay for this upgrade to prevent rework. what is your thought on this? 
Will you continue working on this branch or create a new one after optimization work?

2023-11-07 09:34 UTC, awais-ansari commented
@Syed-Ali-Abbas-Zaidi You can start working on this PR.

2023-11-28 17:32 UTC, sundasnoreen12 requested changes
These routes display a blank content area in cases where the topic or category does not have any units.

http://localhost:2002/course-v1:edX+DemoX+Demo_Course/topics/i4x-edx-eiorguegnru-course-foobarbaz/posts/

http://localhost:2002/course-v1:edX+DemoX+Demo_Course/category/block-v1:edX+DemoX+Demo_Course+type@sequential+block@edx_introduction/posts

<img width="1206" alt="Screenshot 2023-11-28 at 10 23 15 PM" src="https://github.com/openedx/frontend-app-discussions/assets/72802712/f3195812-4379-4190-9968-eea5af1537b7">


These routes display a blank post content area when topic or category have units.
http://localhost:2002/course-v1:edX+DemoX+Demo_Course/topics/i4x-edx-eiorguegnru-course-foobarbaz/posts/

http://localhost:2002/course-v1:edX+DemoX+Demo_Course/category/block-v1:edX+DemoX+Demo_Course+type@sequential+block@19a30717eff543078a5d94ae9d6c18a5/posts

<img width="1202" alt="Screenshot 2023-11-28 at 10 21 17 PM" src="https://github.com/openedx/frontend-app-discussions/assets/72802712/4d4fa75b-42e1-4f1c-a353-7daea1dcc877">

2023-11-29 07:51 UTC, Syed-Ali-Abbas-Zaidi commented on src/discussions/learners/LearnersView.jsx
>          )}
This is the existing code snippet I have just replaced `Redirect` with `Navigate`. But you are right that this component will not be accessed if the `learners flag` is disabled. So I guess we can remove this code snippet from this file, As the redirection is already being handled in the sidebar [here](https://github.com/openedx/frontend-app-discussions/blob/master/src/discussions/discussions-home/DiscussionSidebar.jsx#L97).

2023-11-29 10:01 UTC, Syed-Ali-Abbas-Zaidi commented on src/discussions/posts/post/PostLink.jsx
> +  const { search } = useLocation();
There was some refactoring in the `Link` component of the react-router. Due to this, it does not handle URL query parameters on its own, which is why I explicitly destructured the URL param and passed it to the link component.

2023-11-29 10:01 UTC, Syed-Ali-Abbas-Zaidi commented on src/discussions/topics/topic-group/TopicGroupBase.jsx
> +  const { search } = useLocation();
There was some refactoring in the `Link` component of the react-router. Due to this, it does not handle URL query parameters on its own, which is why I explicitly destructured the URL param and passed it to the link component.

2023-11-30 08:11 UTC, sundasnoreen12 commented on src/data/constants.js
>        topics: `${BASE_PATH}/topics/:topicId/posts/:postId`,
above comment is for line number 186: ${BASE_PATH}/category/:category,
issue still exists

2023-11-30 08:58 UTC, Syed-Ali-Abbas-Zaidi commented
> The [route](http://localhost:2002/course-v1:edX+DemoX+Demo_Course/category) is crashing; it should redirect to All Posts for both legacy and new edX.

Fixed. 🤞

2023-12-04 12:38 UTC, sundasnoreen12 approved these changes
PR LGTM

2023-12-06 14:34 UTC, awais-ansari requested changes
Some routes are breaking and unexpected behavior. I have listed down all the router bugs and expected behavior in [this doc](https://docs.google.com/spreadsheets/d/1uGR4_zS9bZjlprZt_g-80Mqssd_GZu8Iok3AoAp_XTM/edit?usp=sharing).

2023-12-07 12:46 UTC, awais-ansari approved these changes

2023-12-07 13:10 UTC, merged