feat: Profile image on user posts (palm.master)
openedx/frontend-app-discussions pull request #574
Opened 2023-10-11 16:18 UTC by vladislavkeblysh

[### Description

- Added profile image on user avatar posts

![Screenshot 2023-10-11 at 19 01 23](https://github.com/openedx/frontend-app-discussions/assets/138868841/0c815a37-4ed1-4d03-bc16-ad4d992cf312)
](feat: Profile image on user posts (palm.master))

2023-10-11 16:18 UTC, openedx-webhooks commented
Thanks for the pull request, @vladislavkeblysh!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-10-17 14:37 UTC, itsjeyd commented
Hey @vladislavkeblysh, thank you for this contribution!

@jmakowski1123 This seems to be a user-facing change, so we would need a feature ticket for it. Could you please create one?

* Palm backport: #573 
* Quince backport: #575 

CC @mphilbrick211

2023-11-02 10:03 UTC, itsjeyd commented
@jmakowski1123 When you get a minute could you please create a feature ticket for this PR and the backports listed [above](https://github.com/openedx/frontend-app-discussions/pull/574#issuecomment-1766554531)?

2023-11-17 08:24 UTC, itsjeyd commented
@jmakowski1123 @awais-ansari It [sounds like](https://github.com/openedx/frontend-app-discussions/pull/575#issuecomment-1801950004) product review for this PR has already started (?). If so, could you point me to where that conversation is happening? It doesn't seem like we have a feature ticket for this PR, so it's hard for me to tell what its current status is.

CC @mphilbrick211

2023-12-01 11:22 UTC, nedbat commented
I can let Product handle the question in more detail, but my understanding is that some sites don't want this due to privacy concerns, so it may need to be the operator's choice whether to enable it.

2023-12-14 01:01 UTC, jmakowski1123 commented
Apologies for the delay. Lots of open questions regarding this PR, please see here: https://github.com/openedx/platform-roadmap/issues/314

2023-12-14 09:17 UTC, itsjeyd commented
Thanks a lot for the update and product feedback @jmakowski1123! 🙂 

@vladislavkeblysh Product review will continue via https://github.com/openedx/platform-roadmap/issues/314, the feature ticket for this PR. Please have a look at that ticket when you can and address the questions raised in [this comment|https://github.com/openedx/platform-roadmap/issues/314#issuecomment-1854930337].

2024-12-10 16:43 UTC, vladislavkeblysh commented
Ready to review!

2024-12-23 14:05 UTC, awais-ansari requested changes

2025-02-17 10:27 UTC, vladislavkeblysh commented on src/discussions/post-comments/comments/comment/CommentHeader.jsx
> +  const profileImage = getConfig().ENABLE_PROFILE_IMAGE === 'true' && postUsers && Object.values(postUsers)[0].profile.image;
I think it’s better to leave it as is because it’s a more secure check.

2025-08-27 08:50 UTC, awais-ansari commented
> Hi @awais-ansari @vladislavkeblysh this is our oldest PR in the Open edX project 😅
> 
> Any chance I could get an update on where we're at with this? Looks like we're good to go (per the product ticket), but there are branch conflicts and failing tests.

Hello @sarina, PR looks good after recent changes. The only blocker to approving this PR is the failing test case checks. Once these are clear, I will approve and merge it.

2025-08-27 13:06 UTC, sarina commented
@vladislavkeblysh will you be available to resolve conflicts and fix failing tests? cc @cmltaWt0

2025-09-16 20:47 UTC, cmltaWt0 commented
> @cmltaWt0 are you planning to take over this PR? We haven't had a response in 3 weeks so if I don't hear from you in a few days I am going to go ahead and close this.

@sarina sorry, missed it. Give me a day - I'll come back tomorrow with a decision whether I'll push it forward or close.

2025-09-17 08:42 UTC, cmltaWt0 commented
@sarina don't close the PR please, @vladislavkeblysh is going to resolve conflicts and fix tests.

2025-09-24 05:32 UTC, vladislavkeblysh commented
@sarina branch updated

2025-09-24 12:56 UTC, sarina commented
@vladislavkeblysh please tag @awais-ansari . He said,

> The only blocker to approving this PR is the failing test case checks. Once these are clear, I will approve and merge it.

2025-09-25 05:26 UTC, awais-ansari approved these changes

2025-09-25 18:09 UTC, merged