chore: removed enable_learners_tab_in_discussions_mfe flag dependency
openedx/frontend-app-discussions pull request #637
Opened 2024-01-04 13:46 UTC by ayesha-waris

[INF-1185](https://2u-internal.atlassian.net/browse/INF-1185)

## Description

Removed `discussions.enable_learners_tab_in_discussions_mfe `dependency in MFE

2024-01-04 16:49 UTC, sundasnoreen12 requested changes
Please remove this flag dependency from test files also.
PostLink.test.jsx
PostsView.test.jsx
LearnersView.test.jsx
DiscussionsHome.test.jsx
AuthorLabel.test.jsx

2024-01-04 16:49 UTC, sundasnoreen12 commented on src/discussions/discussions-home/DiscussionSidebar.jsx
>            )}
remove square brackets.
       {
            [ROUTES.LEARNERS.POSTS, ROUTES.LEARNERS.POSTS_EDIT].map((route) => (
              <Route key={route} path={route} element={<LearnerPostsView />} />
            ))
          }

2024-01-04 16:49 UTC, sundasnoreen12 commented on src/discussions/discussions-home/DiscussionSidebar.jsx
> +  useContainerSize, useIsOnDesktop, useIsOnXLDesktop,
move these into single line

2024-01-05 10:34 UTC, awais-ansari approved these changes
Just small nits as mentioned by Sundas other than LGTM.

2024-01-05 11:31 UTC, sundasnoreen12 approved these changes
PR LGTM. 
please rebase the PR with master

2024-01-05 12:38 UTC, merged