feat: modified TA icon according to role
openedx/frontend-app-discussions pull request #664
Opened 2024-02-12 14:34 UTC by sohailfatima

[INF-737](https://2u-internal.atlassian.net/browse/INF-737)

### Description

Modified TA icons to include tool-tips and add a moderator label.
Corresponding backend PR: https://github.com/openedx/edx-platform/pull/34218

#### Before:
https://github.com/openedx/frontend-app-discussions/assets/68312464/e8c6fef1-3cb1-4720-92c7-3bb670b94342

#### After:
https://github.com/openedx/frontend-app-discussions/assets/68312464/b6c1559e-cf75-498c-a9e7-ef7457f4a83e

2024-02-12 18:20 UTC, sundasnoreen12 requested changes

2024-02-12 18:20 UTC, sundasnoreen12 commented on src/discussions/common/AuthorLabel.jsx
> +      }
avoid duplication
overlay={
  <Tooltip id={authorToolTip ? `endorsed-by-${author}-tooltip` : `${authorLabel}-role-tooltip`}>
    {authorToolTip ? author : authorLabel}
  </Tooltip>
}

2024-02-12 18:20 UTC, sundasnoreen12 commented on src/discussions/common/AuthorLabel.jsx
> +
avoid multiple if statements here. optimize the code like this 

const labelMappings = {
  Staff: {
    icon: Institution,
    authorLabelMessage: intl.formatMessage(messages.authorLabelStaff),
  },
  Moderator: {
    icon: School,
    authorLabelMessage: intl.formatMessage(messages.authorLabelModerator),
  },
  'Community TA': {
    icon: School,
    authorLabelMessage: intl.formatMessage(messages.authorLabelTA),
  },
};

const labelInfo = labelMappings[authorLabel] || {};
const { icon, authorLabelMessage } = labelInfo;

2024-02-12 18:20 UTC, sundasnoreen12 commented on src/discussions/common/AuthorLabel.test.jsx
> +    ['ta_user', 'Moderator', true, 'text-TA-color'],
I think you should keep the original test case options as it is like 
['ta_user', 'Moderator', true, 'text-TA-color'] and add another test case for 'Moderator'

2024-02-12 18:57 UTC, mphilbrick211 commented
hi @sohailfatima! Thank you for this contribution. Please let me know if you have any questions regarding submitting a CLA form. Thanks!

2024-02-13 06:30 UTC, ayesha-waris commented
> hi @sohailfatima! Thank you for this contribution. Please let me know if you have any questions regarding submitting a CLA form. Thanks!

@mphilbrick211 fatima's CLA form has been submitted, but still have not received any update regarding it.

2024-02-13 09:01 UTC, ayesha-waris requested changes

2024-02-13 09:01 UTC, ayesha-waris commented on src/discussions/common/AuthorLabel.jsx
> +          <Tooltip id={authorToolTip ? `endorsed-by-${author}-tooltip` : `${authorLabel}-role-tooltip`}>
`${authorLabel}-label-tooltip`} can be considered

2024-02-13 18:31 UTC, ehuthmacher commented
@sohailfatima I have not received your CLA form submission. Could you kindly resubmit the form?

2024-02-14 17:34 UTC, sundasnoreen12 approved these changes

2024-02-14 19:27 UTC, awais-ansari requested changes

2024-02-15 09:19 UTC, ayesha-waris approved these changes
LGTM

2024-02-15 11:08 UTC, awais-ansari approved these changes

2024-02-15 11:37 UTC, ayesha-waris commented
created another PR due to CLA https://github.com/openedx/frontend-app-discussions/pull/665

2024-02-15 11:37 UTC, closed without merging

2024-02-15 13:01 UTC, ehuthmacher commented
@sohailfatima Received, thank you. It is processing with our Legal department now.