feat: restricted unnecessary api calls
openedx/frontend-app-discussions pull request #683
Opened 2024-03-27 07:23 UTC by sundasnoreen12

[INF-1295](https://2u-internal.atlassian.net/browse/INF-1295)

### Description

Need following Improvements for the "Content Unavailable" Screen in the Discussion MFE and In-Context Sidebar.

**A.C**

1. Optimized API calls by restricted unnecessary parallel requests, only invoking the API returning the isEnroll attribute when needed, and prevented additional calls.
3. Ensured that unavailable content within the in-context sidebar remains hidden across all use cases.

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2024-03-29 11:51 UTC, awais-ansari requested changes

2024-03-29 11:51 UTC, awais-ansari commented on src/discussions/discussions-home/DiscussionsHome.jsx
> +            !isEnrolled && isUserLearner && !enableInContextSidebar ? (
You can remove Extra condition

2024-04-01 19:16 UTC, awais-ansari commented on src/discussions/data/selectors.js
> +export const selectIsUserLearner = courseStatus => createSelector(
use a selector to get `courseStatus` instead of passing it as param.

2024-04-03 10:19 UTC, awais-ansari approved these changes

2024-04-04 07:42 UTC, muhammadadeeltajamul approved these changes

2024-04-04 07:42 UTC, merged

2024-04-04 10:56 UTC, ayesha-waris approved these changes