fix: responsiveness of MFE discussions
openedx/frontend-app-discussions pull request #697
Opened 2024-05-08 12:52 UTC by ayesha-waris

[INF-1363](https://2u-internal.atlassian.net/browse/INF-1363)
### Description
Identified a few areas where the Discussions MFE could be improved in terms of responsiveness.

fix sidebar width for xl screen i.e greater than 1400 px 
fix inconsistency of font-size, for tablet and mobile change font-size to 12px default and reduce 2 px if other than 12px font
fix actions-dropdown width for all views
fix search field width for mobile and tablet views

2024-05-16 10:27 UTC, sundasnoreen12 requested changes

2024-05-20 09:30 UTC, awais-ansari approved these changes

2024-05-22 07:23 UTC, sundasnoreen12 approved these changes

2024-05-27 11:48 UTC, merged

2024-05-28 08:49 UTC, ayesha-waris commented on src/discussions/posts/post-filter-bar/PostFilterBar.jsx
> +    <Icon src={Check} className={classNames('text-success dropdown-icon-dimensions', { invisible: value !== selected })} />
yes this was intentional for displaying all filter on each field