Sundas/inf 1444
openedx/frontend-app-discussions pull request #727
Opened 2024-07-04 17:51 UTC by sundasnoreen12

[INF-1444](https://2u-internal.atlassian.net/browse/INF-1444)
### Description

Learners using the discussion board have faced a frustrating issue: losing their work when switching tabs and returning to the post. This can be especially disheartening for those writing lengthy comments or responses. The issue occurs specifically while writing comments or responses on posts.

Solution 

Draft Feature: Offering a draft functionality where users can save unfinished posts and return to them later. The draft only be saved on the frontend and are lost on page reload.

#### Screenshots/sandbox (optional):
[Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**](https://www.loom.com/share/fa0007a967ea406f89835409009dd3b1?sid=6207893c-e326-4de8-9abd-7aa053d9a8ee)

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

2024-07-10 10:54 UTC, awais-ansari requested changes

2024-07-10 10:54 UTC, awais-ansari commented on src/discussions/post-comments/data/slices.js
> +    },
Slice:
draftResponses: {}
draftComments: {}

Example:
draftComments: {
  comment1 : {
    id: comment1,
    parentId: response1,
    content: "some content",
    postId: post1
  },
}

draftResponses: {
  response1: {
    id: response1,
    parentId: comment1,
    content: "some content",
    postId: post1
  }
}

Access Example: 
commnet1 = draftComments.?[draftId]
response1 = draftResponses.?[draftId]

Working Example

newComment = {
  id: comment1,
  parentId: response1,
  content: "some content",
  postId: post1
}

addIntoDraftComments(newComment)  // add into draftComments

addIntoDraftComments(newComment) {
  draftComments = {
    ...draftComments,
    [newComment.id]: newComment
  }
}

removeFromDraftComments(newComment) {
  const { removeComment, ...RemainingDraftCommnets} = draftComments
  return RemainingDraftCommnets;
}

2024-07-12 12:33 UTC, awais-ansari requested changes

2024-07-18 09:28 UTC, awais-ansari requested changes

2024-07-18 09:28 UTC, awais-ansari commented on src/discussions/post-comments/comments/comment/CommentEditor.jsx
> +  };
Move it to utils.

2024-07-18 09:28 UTC, awais-ansari commented on src/discussions/post-comments/comments/comment/CommentEditor.jsx
> +    initialValues.comment = draftHtml;
`setEditorContent` will cause a re-rendering and a comment value will get assigned.

2024-07-18 09:28 UTC, awais-ansari commented on src/discussions/post-comments/comments/comment/CommentEditor.jsx
> +  const DeleteEditorContent = async () => {
DeleteEditorContent => deleteEditorContent

2024-07-18 09:59 UTC, awais-ansari requested changes

2024-07-18 09:59 UTC, awais-ansari commented on src/discussions/post-comments/comments/comment/CommentEditor.jsx
> +  const draftContent = useDraftContent();
const { addDraftContent, getDraftContent, removeDraftContent } = useDraftContent();

2024-07-18 09:59 UTC, awais-ansari commented on src/discussions/post-comments/comments/comment/CommentEditor.jsx
> +              saveDraftContent(typeof content === 'object' ? content.target.getContent() : content);
refactor it
saveDraftContent(typeof content === 'object' ? content.target.getContent() : content);
`saveDraftContent(content)`

2024-07-18 11:45 UTC, awais-ansari requested changes

2024-07-18 11:45 UTC, awais-ansari commented on src/discussions/post-comments/comments/comment/CommentEditor.jsx
> +
Apply function memorization.

2024-07-19 09:44 UTC, awais-ansari approved these changes

2024-07-19 09:44 UTC, awais-ansari commented on src/discussions/post-comments/comments/comment/CommentEditor.jsx
> +
Please memorize this function too.

2024-07-22 18:12 UTC, ayesha-waris commented on src/discussions/post-comments/data/hooks.js
> +    }
please consider a method for statements within if and else, the statements appear to be redundant
```
const commentObj = id ? comments[id] : getObjectByParentId(comments, parentId, true, id);
      if (commentObj) {
        updatedComments = removeItem(comments, commentObj.id);
      }
```
```
const responseObj = id ? responses[id] : getObjectByParentId(responses, threadId, false, id);
      if (responseObj) {
        updatedResponses = removeItem(responses, responseObj.id);
}

2024-07-24 09:37 UTC, ayesha-waris approved these changes

2024-07-24 09:40 UTC, awais-ansari requested changes
Please do some refactoring in test cases.

2024-07-24 09:40 UTC, awais-ansari commented on src/discussions/post-comments/PostCommentsView.test.jsx
> +    });
Refactoring
````
await act(async () => {
        fireEvent.click(screen.queryByText('Add comment'));
});

await act(async () => {
        fireEvent.click(screen.queryByText('Cancel'));
 });

await act(async () => {
   fireEvent.click(screen.queryByText('Add comment'));
 );

OR

const addCommentBtn = screen.queryByText('Add comment');
await act(async () => {
        fireEvent.click(addCommentBtn);
      });
      
await act(async () => {
        fireEvent.click(screen.queryByText('Cancel'));
 });
 
 await act(async () => {
        fireEvent.click(addCommentBtn);
      });

2024-07-24 11:47 UTC, awais-ansari approved these changes

2024-07-24 12:24 UTC, merged